### ISSUE TITLE
issue in local installation: Multi-user over LAN

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#1335]
South Asian Centre for Legal Studies

contact person: Chrishanthan Daniel chrishanthan.daniel@gmail.com

UWAZI is accessible over the LAN, but when keying in the username and password from a machine on the network, the authentication is failing. So currently we are limited to use it directly on the server machine only.

It seems to me that the server is not responding to requests that come from other machines in the same network. Maybe Mongo db is blocking the requests?

**Comment by daneryl** [comment]
@bertver I will need to see the error the server is returning, is it a failed login or something else ?

**Comment by habbes** [comment]
I may be wrong, but I think this issue is due to Uwazi making the XHR API requests using the `localhost` domain of the main computer while being accessed via a different IP address from other computers on the network. Changing the `API_URL` to `/api` rather than a fully qualified domain has worked for me locally.

**Comment by chrisha88** [comment]
@daneryl, it is a failed login. It just says that the username and/or password is incorrect

**Comment by chrisha88** [comment]
@daneryl, how can I change the host address in the setup of UWAZI? from _localhost_ to an local IP address such as _192.168.8.XXX_.
Will that fix the issue?

**Comment by daneryl** [comment]
@chrisha88 change the the config file "app/react/config.js" as @habbes say, just: 
export default {APIURL: '/api/'};

**Comment by chrisha88** [comment]
@daneryl, I updated the app/react/config.js file and also keyed in the ip address on behalf of "localhost" as suggested by @RafaPolit, but I am getting the same issue I get on the other machines. Looks like the database is not accepting the values from any other client except 'localhost'. Is there a database configuration I need to fix?

**Comment by daneryl** [comment]
@chrisha88 i need to see pls what errors you have in the browser console.

**Comment by chrisha88** [comment]
@daneryl will send you the screenshots to your email

**Comment by daneryl** [comment]
@chrisha88 it seems it is not properly configured.

> change the the config file "app/react/config.js" as @habbes say, just:
> export default {APIURL: '/api/'};

and remember to rebuild the project with webpack, just launch webpack on the root project folder, then restart the server, it should fix the issue.

**Comment by chrisha88** [comment]
Hi @daneryl it is working now. Is there a limit on the number of users? I created one username and it is working well. I tried creating a 3rd one and it says "An error has occurred".

error console
Headers
Response
Cookies
Connectionkeep-aliveContent-Length114Content-Typeapplication/json; charset=utf-8DateMon, 20 Nov 2017 06:37:09 GMTETagW/"72-tf7iDDgW++O1Km62dpWAKB3y2oc"VaryAccept-EncodingX-Powered-ByExpress
Acceptapplication/jsonAccept-Encodinggzip, deflateAccept-Languageen-GB,en;q=0.5Connectionkeep-aliveContent-Length71Cookieio=duaZ34zh2XpugSLcAAAj; connect.sid=s%3A1T7-rMjMthLmT3IFXJaoTIuShqNtKIFL.aUAMNQseCK1QbhOuXhNws6llS3Cq3dWAfwo8M4TeSzI; locale=enHost192.168.8.102:3000Refererhttp://192.168.8.102:3000/en/settings/users/newUser-AgentMozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0content-languageencontent-typeapplication/jsonoriginhttp://192.168.8.102:3000

Error in parsing value for 'transition'.  Declaration dropped.

**Comment by daneryl** [comment]
@chrisha88 we had a bug some weeks ago that prevented creating more users, its solved now, git pull master to get latest updates, then build the project with webpack and restart the server.

**Comment by bertver** [comment]
comment from chrisha88:
I executed git pull and ran Webpack again.

When I ran node server.js I am getting the following error. 

"
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/dell/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

**Comment by chrisha88** [comment]
@daneryl as per your instructions I tried to reindex elastic search but getting the following error.
> 
/home/dell/uwazi/node_modules/mongoose/node_modules/mongodb/lib/mongo_client.js:389
          throw err
          ^

Error: Cannot find module '../../../../app/api/config/elasticIndexes'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/app/api/search/search.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/database/reset_elastic_index.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
> 

Also when running node server.js getting the below error

> 
module.js:471
    throw err;
    ^

Error: Cannot find module 'react-sticky-el'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/app/react/Relationships/components/RelationshipsGraph.js:4:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/app/react/ConnectionsList/components/ConnectionsList.js:9:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dell/uwazi/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
>

**Comment by daneryl** [comment]
@chrisha88 every time you update the project you need to install the dependencies in case there i new ones.
exeute from the root project directory:

yarn install
webpack
node server.js

**Comment by danicatalan** [comment]
Closing this issue as it will be fixed once those commands are executed.

@chrisha88 please contact @bertver if you still have any doubt about this.
