### ISSUE TITLE
Problem with Webpack

### ISSUE THREAD

**Issue by houshuang** [huridocs/uwazi#1349]
After installing Uwazi (yarn install, database fixtures), I try running foreman start in the root directory, and get this:

```bash
17:13:57 webpack.1 | Webpack is watching the files…
17:13:57 webpack.1 |
17:13:59 server.1  | module.js:529
17:13:59 server.1  |     throw err;
17:13:59 server.1  |     ^
17:13:59 server.1  |
17:13:59 server.1  | Error: Cannot find module '../../dist/webpack-assets.json'
17:13:59 server.1  |     at Function.Module._resolveFilename (module.js:527:15)
17:13:59 server.1  |     at Function.Module._load (module.js:476:23)
17:13:59 server.1  |     at Module.require (module.js:568:17)
17:13:59 server.1  |     at require (internal/module.js:11:18)
17:13:59 server.1  |     at Object.<anonymous> (/Users/stian/src/uwazi/app/react/ServerRouter.js:18:1)
17:13:59 server.1  |     at Module._compile (module.js:624:30)
17:13:59 server.1  |     at loader (/Users/stian/src/uwazi/node_modules/babel-register/lib/node.js:144:5)
17:13:59 server.1  |     at Object.require.extensions.(anonymous function) [as .js] (/Users/stian/src/uwazi/node_modules/babel-register/lib/node.js:154:7)
17:13:59 server.1  |     at Module.load (module.js:545:32)
17:13:59 server.1  |     at tryModuleLoad (module.js:508:12)
17:13:59 server.1  |     at Function.Module._load (module.js:500:3)
17:13:59 server.1  |     at Module.require (module.js:568:17)
17:13:59 server.1  |     at require (internal/module.js:11:18)
17:13:59 server.1  |     at Object.<anonymous> (/Users/stian/src/uwazi/app/react/server.js:1:1)
17:13:59 server.1  |     at Module._compile (module.js:624:30)
17:13:59 server.1  |     at loader (/Users/stian/src/uwazi/node_modules/babel-register/lib/node.js:144:5)
17:13:59 server.1  |     at Object.require.extensions.(anonymous function) [as .js] (/Users/stian/src/uwazi/node_modules/babel-register/lib/node.js:154:7)
17:13:59 server.1  |     at Module.load (module.js:545:32)
17:13:59 server.1  |     at tryModuleLoad (module.js:508:12)
17:13:59 server.1  |     at Function.Module._load (module.js:500:3)
17:13:59 server.1  |     at Module.require (module.js:568:17)
17:13:59 server.1  |     at require (internal/module.js:11:18)
17:13:59 server.1  | [nodemon] app crashed - waiting for file changes before starting...
```

After this, it does seem to be compiling a bunch of files, but it never seems to begin serving them (no connection on localhost:3000).

Thanks for any help!

**Comment by habbes** [comment]
I think the server starts before webpack completes compilation. After you notice webpack has completed compiling you can enter `rs` in the cli and nodemon will restart the server.

**Comment by daneryl** [comment]
@houshuang sorry the procfile is deprecated, you should wait for webpack to build the project and then start the server.

**Comment by txau** [comment]
Closing as solved.
