### ISSUE TITLE
Fix loading bar CSS glitch

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1490]
![screen shot 2018-02-27 at 16 43 08](https://user-images.githubusercontent.com/489831/36759583-80ba1d10-1bdd-11e8-96f3-eb655e73051d.png)

**Comment by chrisha88** [comment]
After running git pull and installing yarn, the following error popped up when building the project using webpack

`module.js:471
    throw err;
    ^

Error: Cannot find module 'optimize-css-assets-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/webpack.production.config.js:6:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`
CSS is not there in the home page of UWAZI itself

**Comment by danicatalan** [comment]
Hi @chrisha88,

Seems that this is not related to the loading glitch. As webpack is not compiling, the CSS should not load at all. You should fix this error related to this module:

`Error: Cannot find module 'optimize-css-assets-webpack-plugin'`

It seems there is a module missing in your project, but I can't help you fixing this. Can you open a new issue to review it? Thanks!
