### ISSUE TITLE
Error: Cannot find module '../../../database/app/shared/comonProperties'

### ISSUE THREAD

**Issue by mtuchi** [huridocs/uwazi#1535]
When trying to launch the application i get 
```
yarn dev-server

Error: Cannot find module '../../../database/app/shared/comonProperties'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mtuchi/GitHub/uwazi/app/api/search/search.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/mtuchi/GitHub/uwazi/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mtuchi/GitHub/uwazi/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mtuchi/GitHub/uwazi/app/api/entities/entities.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/home/mtuchi/GitHub/uwazi/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mtuchi/GitHub/uwazi/node_modules/babel-register/lib/node.js:154:7)
```

node -v  => 6.9.5
MongoDB shell version v3.6.3

**Comment by mtuchi** [comment]
My `elasticsearch` version 
```
{
  "name" : "orqtq9d",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "azh_nEqTR4GM5FpRMI0EVw",
  "version" : {
    "number" : "5.6.8",
    "build_hash" : "688ecce",
    "build_date" : "2018-02-16T16:46:30.010Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by RafaPolit** [comment]
Good morning.  We have found this may be an issue with certain Linux distributions.  This is not happening in Ubuntu, but Debian is showing this error as part of a path resolver error.

We have fixed this in a new version which is launching today.

Once we are sure it is working as expected (about 5 hours from now), I'll write back with the new instructions to reindex the elastic index and launching the application.  Sorry for the troubles.

Best regards,
Rafa.

**Comment by RafaPolit** [comment]
At any rate, this should not be happening with the dev-server script.  It may be an issue with nodemon?

To troubleshoot this please run the following:

Could you please, update the repo with the latest changes and run (from within the root of the project):
```
$ git checkout master
$ git pull origin master
$ sudo npm install -g yarn
$ yarn install
$ node run_migration.js
$ yarn reindex
$ yarn hot
```
This should mostly use local dependencies instead of possibly deprecated global packages (except for yarn which is updated in the third line of instructions).

Please report back.

Thank you,
Rafa.

**Comment by mtuchi** [comment]
Thanks @RafaPolit 
I had to change the `search.js` file yesterday for the setup to work, i have tested the updates from master :point_up: it worked fine.
