### ISSUE TITLE
Research this error

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1789]
https://atlas-of-torture.org/en/library/?q=(filters:(document_types:(and:!t),themes:(values:!(fd2291fe-738c-4e40-803f-207b12e2e0c3))),order:asc,sort:title,types:!(%275b319677a458412442fe0767%27))

Produces this error on the server side:

2018-07-12T19:50:37.702Z [atlas-of-torture] TypeError: Cannot read property 'includes' of undefined
    at Object.multiselectFilter (/srv/datadisk17/uwazi/atlas-of-torture/current/app/api/search/documentQueryBuilder.js:201:11)
    at filters.forEach.filter (/srv/datadisk17/uwazi/atlas-of-torture/current/app/api/search/documentQueryBuilder.js:408:24)
    at Array.forEach (native)
    at Object.filterMetadata (/srv/datadisk17/uwazi/atlas-of-torture/current/app/api/search/documentQueryBuilder.js:397:15)
    at Promise.all.then (/srv/datadisk17/uwazi/atlas-of-torture/current/app/api/search/search.js:132:22)
    at process._tickCallback (internal/process/next_tick.js:103:7)

A quick diagnose reveals that this part of the query is the culprit:

"document_types:(and:!t),"

**Comment by txau** [comment]
Will reopen if the error persists.
