### ISSUE TITLE
Cannot read property "compilation" of undefined

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1964]
```
jr@uwazi:~/uwazi$ yarn production-build
yarn run v1.10.1
warning ../package.json: No license field
$ NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors
/home/jr/uwazi/node_modules/webpack/bin/webpack.js:339
			throw e;
			^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (/home/jr/uwazi/node_modules/last-call-webpack-plugin/src/index.js:170:20)
    at Compiler.apply (/home/jr/uwazi/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/jr/uwazi/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/home/jr/uwazi/node_modules/webpack/bin/webpack.js:329:15)
    at yargs.parse (/home/jr/uwazi/node_modules/webpack/bin/webpack.js:387:2)
    at Object.Yargs.self.parse (/home/jr/uwazi/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/home/jr/uwazi/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

**Comment by vasyugan** [comment]
I guess this is a matter of insufficient instructions.
