### ISSUE TITLE
webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1965]
```
jr@uwazi:~/uwazi$ yarn production-build
yarn run v1.10.1
$ NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors
/home/jr/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (/home/jr/node_modules/webpack/lib/webpack.js:185:10)
    at module.exports (/home/jr/uwazi/webpack/config.js:122:28)
    at Object.<anonymous> (/home/jr/uwazi/webpack.production.config.js:11:41)
    at Module._compile (/home/jr/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/jr/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/jr/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/home/jr/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /home/jr/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/jr/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/jr/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/home/jr/node_modules/yargs/yargs.js:563:18)
    at /home/jr/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/home/jr/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jr/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by vasyugan** [comment]
I suppose a specific version of webpack has to be installed to avoid this failure. Which one?

**Comment by vasyugan** [comment]
By installing version webpack 3.11 I got a bit further, but shortly before finishing, yarn production-build failed with an error from copy-webpack-plugin. I guess, one also needs an older version of that one?!?

**Comment by vasyugan** [comment]
Again, due to missing instructions
