### ISSUE TITLE
TypeError: Cannot read property 'toJS' of undefined

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2034]
Today I found that my uwazi install had suddenly become unreachable. I find the following the error log:

```
  at <anonymous>(/home/node/uwazi/app/react/ServerRouter.js:87:
    at <anonymous>(/home/node/uwazi/app/react/ServerRouter.js:87:
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-10-18T09:48:23.585Z [uwazi_development] 
TypeError: Cannot read property 'toJS' of undefined
    at I18NMenu.render (/home/node/uwazi/app/react/I18N/components/I18NMenu.js:34:44)
    at d (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:211)
    at ya (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:493)
    at a.render (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:48)
    at a.read (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:288)
    at renderToString (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:6)
    at renderComponentWithRoot (/home/node/uwazi/app/react/ServerRouter.js:38:25)
    at renderPage (/home/node/uwazi/app/react/ServerRouter.js:87:23)
    at _settings2.default.get.then.then.then.catch.then (/home/node/uwazi/app/react/ServerRouter.js:177:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-10-18T09:49:23.592Z [uwazi_development] 
TypeError: Cannot read property 'toJS' of undefined
    at I18NMenu.render (/home/node/uwazi/app/react/I18N/components/I18NMenu.js:34:44)
    at d (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:211)
    at ya (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:493)
    at a.render (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:48)
    at a.read (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:288)
    at renderToString (/home/node/uwazi/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:6)
    at renderComponentWithRoot (/home/node/uwazi/app/react/ServerRouter.js:38:25)
    at renderPage (/home/node/uwazi/app/react/ServerRouter.js:87:23)
    at _settings2.default.get.then.then.then.catch.then (/home/node/uwazi/app/react/ServerRouter.js:177:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-10-18T09:49:48.246Z [uwazi_development] 
uncaught exception or unhandled rejection, Node process finished !!
 TypeError: Cannot read property 'contexts' of undefined
    at model.get.then.languages (/home/node/uwazi/app/api/i18n/translations.js:125:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-10-18T09:51:49.165Z [uwazi_development] 
uncaught exception or unhandled rejection, Node process finished !!
 TypeError: Cannot read property 'contexts' of undefined
    at model.get.then.languages (/home/node/uwazi/app/api/i18n/translations.js:125:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

**Comment by vasyugan** [comment]
Right now I have to see how to access the db in the first place, as node.js immediately crashes and I don't get into the configuration. Seems I have to learn some raw nosql

**Comment by vasyugan** [comment]
@daneryl where in the database is the language configured? a "show collections" shows only those four:
connections
entities
sessions
users

Is the language setting stored in any of them?

**Comment by vasyugan** [comment]
Woah! Something has wrecked my mongodb database. After restoring the last dump, it is working again. So this is not uwazi's fault. But how could this have happened?
