### ISSUE TITLE
no such file or directory, open '/home/XX/uwazi/app/react/../../dist/webpack-assets.json'

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2095]
Just built uwazi in a virtual machine to have a clean environment, and whenever I try to load it in the browser, it crashes. On the console it says: 

```
yarn run v1.12.3
$ export NODE_ENV=production; node server.js
==> Processing system keys...
==> 🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
2018-11-22T16:19:49.039Z [localhost] 
uncaught exception or unhandled rejection, Node process finished !!
 Error: Error: ENOENT: no such file or directory, open '/home/XX/uwazi/app/react/../../dist/webpack-assets.json'
webpack-assets.json do not exists or is malformed !,
                          you probably need to build webpack with the production configuration
    at ReadFileContext._fs2.default.readFile [as callback] (/home/jr/uwazi/app/react/ServerRouter.js:237:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

... and indeed, the file is missing.

**Comment by konzz** [comment]
@vasyugan did you run webpack?

**Comment by vasyugan** [comment]
sorry, my bad. Missed the production-build step..
