### ISSUE TITLE
Setting the wrong context in a component crashes the instance

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2455]
When trying to use a  component for data visualization, setting a random "context" as configuration crashes the instance with the following server error:

```
2019-07-31T02:39:10.969Z [sgbv-ihrda] 
url: /
TypeError: Cannot read property 'find' of null
    at categories.map.item (/srv/datadisk17/uwazi/core/app/react/Charts/utils/arrayUtils.js:58:27)
    at Array.map (<anonymous>)
    at Object.formatDataForChart (/srv/datadisk17/uwazi/core/app/react/Charts/utils/arrayUtils.js:53:21)
    at exports.ListChartComponent.props (/srv/datadisk17/uwazi/core/app/react/Markdown/components/ListChart.js:21:18)
    at d (/srv/datadisk17/uwazi/core/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:26:492)
    at ya (/srv/datadisk17/uwazi/core/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:493)
    at a.render (/srv/datadisk17/uwazi/core/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:48)
    at a.read (/srv/datadisk17/uwazi/core/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:288)
    at renderToString (/srv/datadisk17/uwazi/core/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:6)
    at renderComponentWithRoot (/srv/datadisk17/uwazi/core/app/react/ServerRouter.js:37:25)
    at renderPage (/srv/datadisk17/uwazi/core/app/react/ServerRouter.js:84:23)
    at _settings4.default.get.then.then.then.catch.then (/srv/datadisk17/uwazi/core/app/react/ServerRouter.js:166:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by habbes** [comment]
@txau @RafaPolit 
I've made the following change:
Now when you specify an context that the system does not recognise, the chart will get an empty dataset resulting in an empty chart, but the system will not crash.

The rationale behind this decision was that the chart was already omitting values that did not have labels. Since the lack of a context means none of the data values will have no labels, then all values would be omitted, resulting in an empty dataset.
