### ISSUE TITLE
yarn hot fails with TypeError: Cannot read property 'contexts' of undefined at contexts (/root/uwazi/app/api/i18n/translations.js:93:39)

### ISSUE THREAD

**Issue by vorburger** [huridocs/uwazi#2577]
@konzz @txau @bdittes in the context of #2559 (including #2575) I'm hitting this error - any idea?

This happens after #2576, so perhaps this is just an impact of that, and will go away once that's solved?

I saw that #2024 had a similar error, but I can't quite make sense of what to do.

```
[root@79733dc712e9 uwazi]# yarn hot                                                                                                     
yarn run v1.19.1                                                                                                                        
$ export HOT=true;npm run dev-server & npm run webpack-server                                                                           
npm npmWARN lifecycle The node binary used for scripts is /tmp/yarn--1570828392205-0.5706175686948487/node but npm is using /root/.nvm/v
ersions/node/v8.11.4/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.                                                                                                                               
 WARN lifecycle The node binary used for scripts is /tmp/yarn--1570828392205-0.5706175686948487/node but npm is using /root/.nvm/version
s/node/v8.11.4/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.                                                                                                                                     

> Uwazi@1.4.1 webpack-server /root/uwazi
> node ./webpack/webpack.server.js 


> Uwazi@1.4.1 dev-server /root/uwazi
> nodemon --ignore 'app/dist/*' --watch 'app/api' --watch 'app/shared' --watch 'app/react/ServerRouter.js' --watch 'app/react/App/Root.j
s'

[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /root/uwazi/app/api/**/* /root/uwazi/app/shared/**/* app/react/ServerRouter.js app/react/App/Root.js
[nodemon] starting `node server.js`
clean-webpack-plugin: /root/uwazi/dist/* has been removed.
==> Processing system keys...
2019-10-11T21:13:15.838Z [localhost] 
uncaught exception or unhandled rejection, Node process finished !!
 TypeError: Cannot read property 'contexts' of undefined
    at contexts (/root/uwazi/app/api/i18n/translations.js:93:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[nodemon] app crashed - waiting for file changes before starting...

webpack built fcc7d9b2f8d92c9e823e in 12213ms
```

**Comment by daneryl** [comment]
@vorburger is this solved for you ? this error happens when there is no translation document created in the database, do you have anything on collection translations ?

**Comment by RafaPolit** [comment]
I belive this was an issue with not having a blank state prior to other processes.

I'm closing this now, if this is still an issue, I will reopen this.  Thanks.
