### ISSUE TITLE
Sync fails if there is a property type relationship 

### ISSUE THREAD

**Issue by daitj** [huridocs/uwazi#3359]
Syncing from private instance to public instance failes if there is a property which is type relationship, but is missing content. I haven't looked into more details but this is what the property object looks like

```
{
  nestedProperties: [],
  _id: xxxxxxxxxxxxxxx,
  label: 'Related Events',
  type: 'relationship',
  inherit: false,
  relationType: 'xxxxxxxxxxxxxxx',
  showInCard: true,
  name: 'related_events',
  id: 'xxxx-xx-xx-xx-xx',
  filter: true
}

```
This is error log:
```
Dec 09 21:08:53 host: 2020-12-10T02:08:53.052Z [uwazi_development]
Dec 09 21:08:53 host: TypeError: Cannot read property 'toString' of undefined
Dec 09 21:08:53 host:     at /uwazi/prod/app/api/sync/syncConfig.js:186:25
Dec 09 21:08:53 host:     at Array.forEach (<anonymous>)
Dec 09 21:08:53 host:     at /uwazi/prod/app/api/sync/syncConfig.js:177:31
Dec 09 21:08:53 host:     at Array.reduce (<anonymous>)
Dec 09 21:08:53 host:     at Object.shouldSync (/uwazi/prod/app/api/sync/syncConfig.js:174:71)
Dec 09 21:08:53 host:     at runMicrotasks (<anonymous>)
Dec 09 21:08:53 host:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:35:20
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
Dec 09 21:08:53 host:     at async /uwazi/prod/app/api/sync/syncWorker.js:29:7
```

I added following code as a workaround for now. I do not know what would be the correct fix. As I am unable to figure out if p.content being missing is already a bug or if the sync code is the one which has bug?

```
              let belongsToSpecificContent = false
              let belongsToGenericContent = false
              if(p.content){
                belongsToSpecificContent =
                p.content.toString() === templateData._id.toString();
                belongsToGenericContent = p.content === '';
              }
```

**Comment by RafaPolit** [comment]
Thanks for the detailed report.

This indeed looks like a bug on our end.  Sync of inherited properties has several nuances that are difficult to address, because you could configure not to sync the template that particular property is pointing to.

I'll look into it a try to provide a solution, as we are expanding the sync system to include conditional options.

**Comment by RafaPolit** [comment]
Estimate 5pts.

**Comment by RafaPolit** [comment]
Thanks once more.  On a recent refactor, we actually abstracted the sync functionality into a new file `processNamespaces.ts`.  The issue has been fixed more or less with the same approach as your solution:
https://github.com/huridocs/uwazi/blob/499b4a923c8fc7ec505f25effc2997e5aa662499/app/api/sync/processNamespaces.ts#L136-L140

Please update to the new version to check if the problem persists.
