### ISSUE TITLE
Migrations (via install.sh) can fail with (apparent) data loss with an authenticated database

### ISSUE THREAD

**Issue by duncanka** [huridocs/uwazi#3365]
If Uwazi is configured with an authenticated database, then if the Uwazi installation is updated using `install.sh`, the migration step fails in a way that can cause data loss. The script outputs the error below, whether or not the DB authentication information has been provided in environment variables. Afterwards, the database and `uploaded_documents` directory both contain the expected file contents, but Uwazi does not list the files.

It's possible there's an easy way to restore the data, but the fundamental problem is that the migration script doesn't check for or use the DB authentication and host information that the main server script does.

A minimal solution should add that functionality to `migrate.ts`. In addition, it would probably be prudent to check for an authenticated database and output more detailed error information and instructions for completeing the migration, and handle the error more gracefully.

The current error output:
```
Updating database schema...
2020-12-14T04:28:31.230Z [localhost] uncaughtException: command find requires authentication
MongoError: command find requires authentication
    at MessageStream.messageHandler (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:263:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
Reindexing ElasticSearch...
Deleting index uwazi_development... [done]
Creating index uwazi_development...
 - Base properties mapping
 - Custom templates mapping
2020-12-14T04:28:35.165Z [localhost] Uncaught Reindex error.
command find requires authentication
Will exit with (1)

Restoring index settings... [done]
2020-12-14T04:28:35.374Z [localhost] uncaughtException: command find requires authentication
MongoError: command find requires authentication
    at MessageStream.messageHandler (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:263:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
```

**Comment by daneryl** [comment]
@duncanka i think the reason for uwazi not listing the files is that the next step after migration is reindex which is failing also because it needs mongodb auth (i suggested on the PR to add this as well), uwazi list is based on the elasticsearch index.

if this is the case then there is no data loss. but i agree that a better handling for this case will improve the experience,
maybe check for access to the DB on the beginning of the script and exit 1 if mongo returns "auth required" ?

**Comment by duncanka** [comment]
We could do that, but don't we also want to grab the config settings to make sure we're hitting the right Mongo instance? I'm not sure it makes sense to do this directly in the install script; might be better with a supporting JS/TS script.
