### ISSUE TITLE
error when loading a document, when one of the references has an empty selectionRectangles array. [2 days]

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3575]
for some reason there are references with empty selectionRectangles, this produces this error when trying to load a document.
```
TypeError: Cannot read property 'page' of undefined
    at sortTextSelections (/opt/uwazi/cores/core-1.26.0-rc1/app/react/Viewer/utils/sortTextSelections.js:2:26)
    at sort (/opt/uwazi/cores/core-1.26.0-rc1/app/react/Viewer/components/ConnectionsList.js:33:20)
    at Array.sort (<anonymous>)
    at ConnectionsList.render (/opt/uwazi/cores/core-1.26.0-rc1/app/react/Viewer/components/ConnectionsList.js:33:5)
    at d (/opt/uwazi/cores/core-1.26.0-rc1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/opt/uwazi/cores/core-1.26.0-rc1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/opt/uwazi/cores/core-1.26.0-rc1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/opt/uwazi/cores/core-1.26.0-rc1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/opt/uwazi/cores/core-1.26.0-rc1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at renderComponentWithRoot (/opt/uwazi/cores/core-1.26.0-rc1/app/react/ServerRouter.js:55:25)
    at renderPage (/opt/uwazi/cores/core-1.26.0-rc1/app/react/ServerRouter.js:114:23)
    at /opt/uwazi/cores/core-1.26.0-rc1/app/react/ServerRouter.js:203:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

how selectionRectangles can be empty i do not know, one option is that the pdfchar to absolute position migration did migrate some of the references wrong and this can never happen on the current state ? either way i think we should make this robust and do not crash the app when this scenario happens ?

**Comment by txau** [comment]
At least not crashing and registering and exception since there should be no empty rectangles. What to do with the faulty ones? Shall we delete them or just report them in the error log? I'm inclined for reporting until we have more info.

Extra ball: check out if they are coming from the migration (probably) or they can actually be created via UI (less likely).

**Comment by daneryl** [comment]
> At least not crashing and registering and exception since there should be no empty rectangles. What to do with the faulty ones? Shall we delete them or just report them in the error log? I'm inclined for reporting until we have more info.

the crash happens on the browser, we do not have a way to report this.

after looking for a while i still do not know the exact cause, but i know that the migration is not the cause, all empty `selectionRectangles` where created after the migration.

An empty `selectionRectangles` is not the issue as this is the default when creating reference without textSelection, what generates the error is a reference with the combination of properties text and `selectionRecrangles` empty.

activity logs show a small number of this references created, this means that somehow the user has properly selected text and saved the reference without properly calculating the `selectionRectangles`, most likely because of some kind of browser incompatibility, there is issues reported on pdfjs about this topic like https://github.com/mozilla/pdf.js/issues/10927 and https://github.com/mozilla/pdf.js/issues/10088, i have tried on edge and everything worked fine for me, with IE11 i can not even log in.

@RafaPolit @txau the fix for the crash is straightforward, but this will mean some references will not have a highlight on the text.
to know more about the original cause i think we should include browser information in the activity log if possible ?


another option that for what is causing this that i have not been able to verify is that we are filtering the selection of tags and removing all divs, since in theory all text rendered by pdfjs is inside spans and not divs, if there is the case where all the text selected is inside divs, then this will also produce an empty selection, this was not the case on the activity log cases reviewed.

**Comment by daneryl** [comment]
the crash fix is goning to be tracked here https://github.com/huridocs/uwazi/issues/3623
