### ISSUE TITLE
Broken activity log (5 points)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3756]
Navigating to the activity log in SUMMA tosses a JS error
```
url: /api/activitylog
query: {}
TypeError: Cannot read property 'originalname' of undefined
    at Object.loadFile [as related] (/opt/uwazi/cores/core-1.31.0/app/api/activitylog/helpers.js:55:73)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ActivityLogBuilder.loadRelated (/opt/uwazi/cores/core-1.31.0/app/api/activitylog/activityLogBuilder.js:53:19)
    at buildActivityEntry (/opt/uwazi/cores/core-1.31.0/app/api/activitylog/activityLogBuilder.js:110:3)
    ```

**Comment by RafaPolit** [comment]
Some of the values get somehow postprocessed.

Please, ensure that all those such scenarios are within a failsafe method (try catch?) and if it fails, it just simply renders the RAW data.
