### ISSUE TITLE
Debug 2511: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4033]
```
2021-11-17T13:35:54.956Z [****] requestId: 2511 
url: /api/search?allAggregations=true&limit=0&include=%5B%22permissions%22%5D
query: {
 "allAggregations": true,
 "limit": 0,
 "include": [
  "permissions"
 ]
}
TypeError: Cannot read property 'type' of undefined
    at filter (/opt/uwazi/cores/core-1.42.1/app/api/search/search.js:72:5)
    at Array.filter (<anonymous>)
    at aggregationProperties (/opt/uwazi/cores/core-1.42.1/app/api/search/search.js:70:3)
    at buildQuery (/opt/uwazi/cores/core-1.42.1/app/api/search/search.js:679:24)
    at Object.search (/opt/uwazi/cores/core-1.42.1/app/api/search/search.js:695:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /opt/uwazi/cores/core-1.42.1/app/api/utils/routesErrorHandler.js:6:5
original error: {}
```

We have notifications for these type of errors in different instances.

**Comment by konzz** [comment]
The error hapens in this code when trying to get the inherited property:
https://github.com/huridocs/uwazi/blob/b2a5801f954827e065b48eb1599d4194f16e3a20/app/api/search/search.js#L68-L73

The scenario on where it happens:
You have two properties with same name and same type:
```js
{_id: 1, lable: 'City', type: 'geolocation'}
{_id: 2, lable: 'City', type: 'geolocation'}
```
Then a relationship property that inherits one of them:
```js
{_id: 3, label: 'Location', type: 'relationship', inherit: { property: 2, type: 'geolocation' }}
````

Then the `getInheritedProperty(property, allUniqueProperties)` receives that property and an array `allUniqueProperties`, this array is all the properties but filtering out properties that match in type and name, so when the method tries to match the property by id, it is not found. and the .type of undefined error is thrown.
