### ISSUE TITLE
Debug 5820: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#4035]
```
2021-11-15T16:22:26.888Z [**] requestId: 5820 
url: /api/references/group_by_connection?sharedId=r9vl5qggp8a
query: {
 "sharedId": "r9vl5qggp8a"
}
TypeError: Cannot read property 'name' of undefined
    at getGroupData (/opt/uwazi/cores/core-1.42.1/app/api/relationships/groupByRelationships.js:9:7)
    at forEach (/opt/uwazi/cores/core-1.42.1/app/api/relationships/groupByRelationships.js:26:23)
    at Array.forEach (<anonymous>)
    at groupRelationships (/opt/uwazi/cores/core-1.42.1/app/api/relationships/groupByRelationships.js:25:17)
    at /opt/uwazi/cores/core-1.42.1/app/api/relationships/relationships.js:225:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
original error: {}
```

**Comment by LaszloKecskes** [comment]
@RafaPolit This is about specific problem in a specific dataset, from almost two years ago. Should we still check it, or close it?

**Comment by txau** [comment]
Let's close and maybe reopen if it happens again
