### ISSUE TITLE
[Tenant error] Error: Accessing nonexistent async context

### ISSUE THREAD

**Issue by blesskn** [huridocs/uwazi#4070]
get this error when i run `yarn blank-state` during uwazi setup.

**Comment by txau** [comment]
@blesskn can you maybe report the whole install process with every command and output?

**Comment by cer-0** [comment]
Hey

We are experiencing the same issue, after unpacking the latest release, upgrading dependencies and migrating we encounter an error when running `yarn reindex`:

```
$ yarn reindex
yarn run v1.22.19
$ node --max-http-header-size 20000 scripts/run.js ../database/reindex_elastic.js
Deleting index uwazi_development...
The index was not found:
{
 "name": "FetchResponseError",
 "json": {
  "error": {
   "root_cause": [
    {
     "type": "index_not_found_exception",
     "reason": "no such index [uwazi_development]",
     "resource.type": "index_or_alias",
     "resource.id": "uwazi_development",
     "index_uuid": "_na_",
     "index": "uwazi_development"
    }
   ],
   "type": "index_not_found_exception",
   "reason": "no such index [uwazi_development]",
   "resource.type": "index_or_alias",
   "resource.id": "uwazi_development",
   "index_uuid": "_na_",
   "index": "uwazi_development"
  },
  "status": 404
 },
 "status": 404,
 "headers": {}
}
Moving on.
 [done]
Creating index uwazi_development...
 - Base properties mapping
2022-10-19T03:16:31.274Z [localhost] Uncaught Reindex error.
Fetch returned a response with status 400.
Will exit with (1)

Restoring index settings... [done]
2022-10-19T03:16:31.351Z [localhost] uncaughtException: Fetch returned a response with status 404.
FetchResponseError: Fetch returned a response with status 404.
    at /home/sd/prod/app/shared/JSONRequest.js:128:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/sd/prod/database/reindex_elastic.js:42:7
[Tenant error] Error: Accessing nonexistent async context
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is with version 1.88.0

I am not sure if I missed something, since I have experienced this error a couple of times now.

Thanks for the help.

**Comment by daneryl** [comment]
@cer-0 im not able to replicate the issue with 1.88.0,  Based on 

```
2022-10-19T03:16:31.274Z [localhost] Uncaught Reindex error.
Fetch returned a response with status 400.
Will exit with (1)
```

looks like elastic search is returning a Bad request error, what version of elasticsearch are you using ? is your mongodb database a blank state one ?

**Comment by cer-0** [comment]
@daneryl Installed version 7.11.2 of elasticsearch before upgrading uwazi, double checked if the elasticsearch daemon was running before running `yarn reindex`.

The mongo DB is not a blank state one, we have actually registered a couple of cases, users and entities. D:

**Comment by RafaPolit** [comment]
@cer-0 Thanks for the patience on this issue.  We are preparing a code change for you to modify the reindex file in order to provide a little bit more debugging info.  We will reach out on Monday with the lines of code and instructions on how modify the file.

In the meantime, AFTER running the `yarn reindex` and getting the error, what is the result of `curl localhost:9200` (or whatever IP:PORT you have installed Elastic Search on)?

**Comment by cer-0** [comment]
@RafaPolit thank you and all the team working on int! (:

Sure, this is the output:

```
$ curl localhost:9200
{
  "name" : "st-uwasi",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "vLoLTYDpScW3khEApJbEKA",
  "version" : {
    "number" : "7.11.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "3e5a16cfec50876d20ea77b075070932c6464c7d",
    "build_date" : "2021-03-06T05:54:38.141101Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```

**Comment by RafaPolit** [comment]
Maybe a longshot, but did you install / update the ICU plugin for ES with your version upgrade?

**Comment by cer-0** [comment]
Hey @RafaPolit , that fixed the reindex issue! I forgot to upgrade the plugin :woman_facepalming:, after that, running `reindex` showed this output:

```
$ yarn reindex                                                                                                                                                                                                               yarn run v1.22.19                                                                                                                                                                                                                              $ node --max-http-header-size 20000 scripts/run.js ../database/reindex_elastic.js                                                                                                                                                              
Deleting index uwazi_development...                                                                                                                                                                                                            
The index was not found:                                                                                                                                                                                                                       
{                                                                                                                                                                                                                                              
 "name": "FetchResponseError",                                                                                                                                                                                                                 
 "json": {                                                                                                                                                                                                                                     
  "error": {                                                                                                                                                                                                                                   
   "root_cause": [                                                                                                                                                                                                                             
    {                                                                                                                                                                                                                                          
     "type": "index_not_found_exception",                                                                              
     "reason": "no such index [uwazi_development]",                                                                    
     "resource.type": "index_or_alias",                                                                                                                                                                                                        
     "resource.id": "uwazi_development",                                                                               
     "index_uuid": "_na_",
     "index": "uwazi_development"
    }
   ],
   "type": "index_not_found_exception",
   "reason": "no such index [uwazi_development]",
   "resource.type": "index_or_alias",
   "resource.id": "uwazi_development",
   "index_uuid": "_na_",
   "index": "uwazi_development"
  },
  "status": 404
 },
 "status": 404,
 "headers": {}
}
Moving on.
 [done]
Creating index uwazi_development...
 - Base properties mapping
 - Custom templates mapping
 [done]
Tweaking index settings for reindex performance... [done]
Starting reindex...
Indexing documents and entities... - 22 indexeded
Restoring index settings... [done]
Done, took 73.626 seconds
Done in 80.81s.
```

Probably upgrading elasticsearch deleted all the previously installed plugins. Anyway, thank you and @daneryl for your help! (:

**Comment by daneryl** [comment]
@cer-0 glad you found the issue, in any case, the error feedback on the reindex script is not enough and we prepared a new release https://github.com/huridocs/uwazi/releases/tag/1.89.2 where the reindex process will print more information when this kind of errors happen in the future.
