### ISSUE TITLE
Review and fix wrong use of getInheritedProperty. (5 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#4173]
Another error related to [getInheritedProperty()](https://github.com/huridocs/uwazi/blob/8382d4067548aa726de552bae9feb592b787cd96/app/shared/comonProperties.js#L75) has been reported in cejil-staging.

> 12:02 PM: 2022-01-24T12:02:24.258Z [cejil-staging] requestId: 1304 
url: /api/search?allAggregations=true&limit=0&include=%5B%22permissions%22%5D
query: {
 "allAggregations": true,
 "limit": 0,
 "include": [
  "permissions"
 ]
}
TypeError: Cannot read property 'content' of undefined
    at map (/opt/uwazi/cores/core-1.50.0-rc1/app/api/search/search.js:81:5)
    at Array.map (<anonymous>)
    at aggregationProperties (/opt/uwazi/cores/core-1.50.0-rc1/app/api/search/search.js:77:3)
    at buildQuery (/opt/uwazi/cores/core-1.50.0-rc1/app/api/search/search.js:677:24)
    at Object.search (/opt/uwazi/cores/core-1.50.0-rc1/app/api/search/search.js:693:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /opt/uwazi/cores/core-1.50.0-rc1/app/api/utils/routesErrorHandler.js:6:5
original error: {}

The problem is the same as in the issue #4033 but just a few lines below where that function is used again.

Some discussion about best aproach to fix this is required.

**Comment by RafaPolit** [comment]
Actually, the `allUniqueProperties` is the real culprit, so please check that that helper is only used where needed as well.
