### ISSUE TITLE
Flaky unit test app/api/csv/specs/csvLoader.spec.js 

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazi#4285]
The above test is sometimes failing on the CI, with a rerun fixing it without changes. Example output:
```
FAIL app/api/csv/specs/csvLoader.spec.js (8.969 s)
  ● csvLoader › on error › should stop processing on the first error

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      200 |
      201 |   describe('on error', () => {
    > 202 |     it('should stop processing on the first error', async () => {
          |     ^
      203 |       const testingLoader = new CSVLoader();
      204 |
      205 |       await db.clearAllAndLoad(fixtures);

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (api/csv/specs/csvLoader.spec.js:202:5)
      at Suite.<anonymous> (api/csv/specs/csvLoader.spec.js:201:3)
      at Object.<anonymous> (api/csv/specs/csvLoader.spec.js:14:1)
```

**Comment by daneryl** [comment]
Not happening anymore, i have run it locally 100 times without a failure, sometimes flakyness has to do with other tests running in parallel, since the logs for this run are no longer there im closing this, lets investigate more if this happens again.
