### ISSUE TITLE
japiqay - cannot rename entity field

### ISSUE THREAD

**Issue by tuxpiper** [huridocs/uwazi#994]
See video for how to reproduce:

https://youtu.be/g1sr2tjOWCU

The following error in the browser console may be related:
```
main.bundle.js:114 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at https://japiqay.uwazi.io/main.bundle.js:114:7564
    at o (https://japiqay.uwazi.io/main.bundle.js:114:17565)
    at o (https://japiqay.uwazi.io/main.bundle.js:114:17654)
    at e (https://japiqay.uwazi.io/main.bundle.js:114:7502)
    at https://japiqay.uwazi.io/main.bundle.js:17:19761
    at https://japiqay.uwazi.io/main.bundle.js:114:12312
    at Array.reduceRight (native)
    at https://japiqay.uwazi.io/main.bundle.js:114:12279
    at https://japiqay.uwazi.io/main.bundle.js:39:3904
```

**Comment by konzz** [comment]
Thanks for reporting this, its been fixed and will be deployed soon.
